language: python
python:
- '3.6'
install:
- pip install -r requirements_devel.txt
- pip install coveralls

branches:
  only:
    - develop
    - master
    - tests
addons:
  postgresql: '9.4'
script:
  - nosetests --rednose --with-coverage --cover-package=models
after_success: coveralls
cache: pip
notifications:
  email: cynthia.abura@andela.com
