"""password

Revision ID: 589c52f5f1ac
Revises: 2885d712a397
Create Date: 2017-04-20 11:06:48.955228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589c52f5f1ac'
down_revision = '2885d712a397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('api')
    op.drop_constraint(None, 'bucketlist_item', type_='foreignkey')
    op.create_foreign_key(None, 'bucketlist_item', 'bucketlist', ['bucketlist_id'], ['id'])
    op.add_column('user', sa.Column('_password', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_password')
    op.drop_constraint(None, 'bucketlist_item', type_='foreignkey')
    op.create_foreign_key(None, 'bucketlist_item', 'api', ['bucketlist_id'], ['id'])
    op.create_table('api',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=300), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bucketlist')
    # ### end Alembic commands ###
