"""tag table

Revision ID: 723fcf4e6f8d
Revises: c38b5bb24386
Create Date: 2017-05-07 20:14:46.207712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723fcf4e6f8d'
down_revision = 'c38b5bb24386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('bucketlist_item_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bucketlist_item_id'], ['bucketlist_item.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('tag')
    # ### end Alembic commands ###
