"""bucketlist id

Revision ID: a641bf299e8d
Revises: ba989dada0cb
Create Date: 2017-05-07 18:05:21.725356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a641bf299e8d'
down_revision = 'ba989dada0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlist_item', sa.Column('bucketlist_id', sa.Integer(), nullable=False))
    op.drop_constraint('bucketlist_item_bucketlist_object_fkey', 'bucketlist_item', type_='foreignkey')
    op.create_foreign_key(None, 'bucketlist_item', 'bucketlist', ['bucketlist_id'], ['id'])
    op.drop_column('bucketlist_item', 'bucketlist_object')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlist_item', sa.Column('bucketlist_object', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bucketlist_item', type_='foreignkey')
    op.create_foreign_key('bucketlist_item_bucketlist_object_fkey', 'bucketlist_item', 'bucketlist', ['bucketlist_object'], ['id'])
    op.drop_column('bucketlist_item', 'bucketlist_id')
    # ### end Alembic commands ###
