"""bucketlist object field

Revision ID: ba989dada0cb
Revises: 9d18c039a538
Create Date: 2017-05-06 15:41:28.753461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba989dada0cb'
down_revision = '9d18c039a538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlist_item', sa.Column('bucketlist_object', sa.Integer(), nullable=False))
    op.drop_constraint('bucketlist_item_bucketlist_fkey', 'bucketlist_item', type_='foreignkey')
    op.create_foreign_key(None, 'bucketlist_item', 'bucketlist', ['bucketlist_object'], ['id'])
    op.drop_column('bucketlist_item', 'bucketlist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlist_item', sa.Column('bucketlist', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bucketlist_item', type_='foreignkey')
    op.create_foreign_key('bucketlist_item_bucketlist_fkey', 'bucketlist_item', 'bucketlist', ['bucketlist'], ['id'])
    op.drop_column('bucketlist_item', 'bucketlist_object')
    # ### end Alembic commands ###
