"""bucketlist item done

Revision ID: c38b5bb24386
Revises: a641bf299e8d
Create Date: 2017-05-07 19:08:24.698033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38b5bb24386'
down_revision = 'a641bf299e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bucketlist', 'description',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.add_column('bucketlist_item', sa.Column('done', sa.Boolean(), nullable=False))
    op.alter_column('bucketlist_item', 'description',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bucketlist_item', 'description',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.drop_column('bucketlist_item', 'done')
    op.alter_column('bucketlist', 'description',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###
