"""tag table name

Revision ID: cfeb0ef5b1af
Revises: 723fcf4e6f8d
Create Date: 2017-05-07 20:35:02.979364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfeb0ef5b1af'
down_revision = '723fcf4e6f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_association',
    sa.Column('bucketlist_item_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bucketlist_item_id'], ['bucketlist_item.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.drop_table('association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('bucketlist_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bucketlist_item_id'], ['bucketlist_item.id'], name='association_bucketlist_item_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='association_tag_id_fkey')
    )
    op.drop_table('tag_association')
    # ### end Alembic commands ###
